import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { memo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { formatBytes, formatDate } from "../utils/formatters";
const FileCard = ({ file, onBackup, onDelete }) => {
    const [expanded, setExpanded] = useState(false);
    return (_jsxs(motion.div, { layout: true, className: "bg-[#161b22] border border-gray-800 rounded-xl p-4 space-y-3", initial: { opacity: 0.7 }, animate: { opacity: 1 }, children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-semibold text-lg", children: file.name }), _jsx("p", { className: "text-sm text-gray-400", children: file.path })] }), _jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx("span", { className: "text-gray-400", children: formatBytes(file.size) }), _jsx("span", { className: `px-2 py-1 rounded-full text-xs capitalize ${file.status === "pending" ? "bg-yellow-500/20 text-yellow-300" : "bg-emerald-500/20 text-emerald-300"}`, children: file.status })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("button", { className: "px-3 py-1 rounded-lg bg-primary/20 text-primary text-sm", onClick: () => onBackup(file.id), children: "Backup now" }), _jsx("button", { className: "px-3 py-1 rounded-lg bg-red-500/20 text-red-300 text-sm", onClick: () => onDelete(file.id), children: "Delete" }), _jsx("button", { className: "ml-auto text-sm text-gray-400", onClick: () => setExpanded((value) => !value), children: expanded ? "Hide versions" : "Show versions" })] }), _jsx(AnimatePresence, { children: expanded && (_jsx(motion.ul, { initial: { height: 0, opacity: 0 }, animate: { height: "auto", opacity: 1 }, exit: { height: 0, opacity: 0 }, className: "space-y-2 border-t border-gray-800 pt-2 text-sm", children: file.versions.map((version) => (_jsxs("li", { className: "flex justify-between text-gray-400", children: [_jsxs("span", { children: [version.delta_hash.slice(0, 10), "..."] }), _jsx("span", { children: formatDate(version.created_at) })] }, version.id))) })) })] }));
};
export default memo(FileCard);
